- hosts: localhost
  connection: local
  tasks:
    - name: Initialize home
      git:
        repo: 'git@github.com:enzuru/home.git'
        dest: '~'
        version: master
        force: yes
    - name: Clone repositories
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop:
        - { repo: 'git@github.com:enzuru/.emacs.d.git', dest: '~/.emacs.d' }
        - { repo: 'git@github.com:enzuru/notes.git', dest: '~/src/notes' }
        - { repo: 'https://github.com/stumpwm/stumpwm-contrib.git', dest: '~/.stumpwm.d/contrib' }
